### ISSUE TITLE
Error elementpath.exceptions.ElementPathTypeError: 'entry' proxy function at line 1, column 18: [err:XPST0017] unknown function 'entry' with sch:let variable XPath 2 expression

### ISSUE THREAD

**Issue by martin-honnen** [robbert-harms/pyschematron#3]
I am having trouble with some sch:let expression using XPath2/3 syntax, for some reasons pyschematron with its underlying elementpath library doesn't seem to be able to process it (not sure whether it is somehow not using the XPath 2 or 3 parser and the XPath 1 parser instead or whether the particular used element name `entry` is messing parsing the XPath expression up).

Run results:
```
 PS C:\Users\marti\PycharmProjects\Pyschematron-test1> pyschematron ..\..\OneDrive\Documents\schematron\examples\sample2.xml ..\..\OneDrive\Documents\schematron\examples\max-count-test4.sch
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Scripts\pyschematron.exe\__main__.py", line 7, in <module>
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\typer\main.py", line 328, in __call__
    raise e
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\typer\main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\typer\core.py", line 721, in main
    return _main(
           ^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\typer\core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\typer\main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\cli.py", line 31, in validate
    result = validate_document(xml_documents[0], schema, phase=phase)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\__init__.py", line 42, in validate_document
    validator = validator_factory.build()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\api.py", line 82, in build
    return DirectModeSchematronValidator(schema, self._phase, schematron_base_path, query_processor_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\api.py", line 155, in __init__
    self._validator = SimpleSchematronXMLValidator(schema, phase, base_path,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 85, in __init__
    self._pattern_validators = self._get_pattern_validators()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 167, in _get_pattern_validators      
    pattern_validators.append(_PatternValidator(self._schema, self._query_parser, pattern))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 186, in __init__
    self._rule_validators: list[_RuleValidator] = self._get_rule_validators()
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 230, in _get_rule_validators
    rule_validators.append(_RuleValidator(self._schema, self._query_parser, rule))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 248, in __init__
    self._variable_evaluators = _get_variable_evaluators(self._rule.variables, self._query_parser)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 542, in _get_variable_evaluators     
    results[variable.name] = _QueryVariableEvaluator(parser.parse(variable.value.query))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\xml_validation\queries\base.py", line 146, in parse
    return self._query_cache.setdefault(source, self._query_parser.parse(source))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\pyschematron\direct_mode\xml_validation\queries\xpath.py", line 69, in parse
    xpath_token = self._parser.parse(source)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\xpath2\xpath2_parser.py", line 510, in parse
    root_token = super(XPath1Parser, self).parse(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\tdop.py", line 497, in parse
    root_token = self.expression()
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\tdop.py", line 622, in expression
    left = self.token.nud()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\xpath_tokens.py", line 1454, in nud
    self._items[k:] = self.parser.expression(5),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\tdop.py", line 625, in expression
    left = self.token.led(left)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\xpath1\_xpath1_operators.py", line 718, in led_child_or_descendant_path
    self[:] = left, self.parser.expression(75)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\tdop.py", line 622, in expression
    left = self.token.nud()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\xpath_tokens.py", line 1454, in nud
    self._items[k:] = self.parser.expression(5),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\tdop.py", line 622, in expression
    left = self.token.nud()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\marti\PycharmProjects\Pyschematron-test1\.venv\Lib\site-packages\elementpath\xpath_tokens.py", line 1204, in nud
    raise self.error('XPST0017', msg) from None
elementpath.exceptions.ElementPathTypeError: 'entry' proxy function at line 1, column 18: [err:XPST0017] unknown function 'entry'

```

Files: XML
```
      <table frame="all" rowsep="1" colsep="1" id="flowers_table">
        <title>Flowers</title>
        <tgroup cols="3">
          <colspec colname="c1" colnum="1" colwidth="1.0*"/>
          <colspec colname="c2" colnum="2" colwidth="1.0*"/>
          <colspec colname="c3" colnum="3" colwidth="1.0*"/>
          <thead>
            <row>
              <entry>Flower</entry>
              <entry>Type</entry>
            </row>
          </thead>
          <tbody>
            <row>
              <entry>Chrysanthemum</entry>
              <entry>perennial</entry>
              <entry>well drained</entry>
            </row>
            <row>
              <entry>Gardenia</entry>
              <entry>perennial</entry>
            </row>
            <row>
              <entry>Gerbera</entry>
              <entry>annual</entry>
              <entry>sandy, well-drained</entry>
            </row>
            <row>
              <entry>Iris</entry>
            </row>
          </tbody>
        </tgroup>
      </table>

```

Schematron

```
<?xml version="1.0" encoding="UTF-8"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt3">
  
  <sch:pattern>

    <!-- Table asserts -->
    <sch:rule context="table">
      <sch:let name="minColumsNo" value="min(.//row/count(entry))"/>
      <sch:let name="reqColumsNo" value="max(.//row/count(entry))"/>

      <!-- Check the number of cells on each row -->
      <sch:assert test="$minColumsNo >= $reqColumsNo">Cells are missing. (The number of cells for
        each row must be <sch:value-of select="$reqColumsNo"/>)</sch:assert>
    </sch:rule>

  </sch:pattern>
</sch:schema>
```

**Comment by martin-honnen** [comment]
That seems indeed an underlying issue in elementpath's XPath3Parser as I can reproduce the error there without using pyschematron: https://github.com/sissaschool/elementpath/issues/78.

So this can most certainly be closed if elementpath gets a fix.

**Comment by robbert-harms** [comment]
Thanks for reporting it to the elementpath library. I will update the dependency as soon as it is fixed.

**Comment by robbert-harms** [comment]
I updated the dependency version. Thank you for notifying me! Closing this, as it seems to be fixed.
