### ISSUE TITLE
Use of xs:integer() constructor on right side of arrow operator fails

### ISSUE THREAD

**Issue by martin-honnen** [robbert-harms/pyschematron#6]
I have a Schematron schema
```
<schema xmlns="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt3">
    <pattern>
        <rule context="item[term[matches(., '^[0-9]+\.$')]][position() gt 1]">
            <assert test="
            let $number := term => substring-before('.') => xs:integer(), 
            $number2 := preceding-sibling::item[1]/term => substring-before('.') => xs:integer() 
            return $number = $number2 + 1">item with <value-of select="term"/> doesn't have the right number.</assert>
        </rule>
        <rule context="item[term[matches(., '^[a-z]+\)$')]][position() gt 1]">
            <assert test="
            let $index := term => substring-before(')') => string-to-codepoints(), 
            $index2 := preceding-sibling::item[1]/term => substring-before(')') => string-to-codepoints()
            return every $bool in for-each-pair($index, $index2, function($a, $b) { $a = $b + 1 }) satisfies $bool">item with <value-of select="term"/> doesn't have the right term.</assert>
        </rule>
    </pattern>
</schema>
```
and an instance
```
<list>
  <item>
    <term>aa)</term>
    <p>jhjhjh hjkjkjkj</p>
  </item>
  <item>
    <term>cc)</term>
    <p>jhjhjh hjkjkjkj</p>
  </item>
  <item>
    <term>dd)</term>
    <p>jhjhjh hjkjkjkj</p>
  </item>
</list>
```

When I run pyschematron (latest version) from the command line it outputs a longish traceback shown below.

It seems like a bug in elementpath but I raise it here as well to get pyschematron updated if the bug in elementpath is identified and fixed.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Scripts\pyschematron.exe\__main__.py", line 7, in <module>
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 328, in __call__
    raise e
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\core.py", line 721, in main
    return _main(
           ^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\cli.py", line 31, in validate
    result = validate_document(xml_documents[0], schema, phase=phase)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\__init__.py", line 42, in validate_document
    validator = validator_factory.build()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\api.py", line 82, in build
    return DirectModeSchematronValidator(schema, self._phase, schematron_base_path, query_processor_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\api.py", line 155, in __init__
    self._validator = SimpleSchematronXMLValidator(schema, phase, base_path,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 85, in __init__
    self._pattern_validators = self._get_pattern_validators()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 167, in _get_pattern_validators
    pattern_validators.append(_PatternValidator(self._schema, self._query_parser, pattern))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 186, in __init__
    self._rule_validators: list[_RuleValidator] = self._get_rule_validators()
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 230, in _get_rule_validators
    rule_validators.append(_RuleValidator(self._schema, self._query_parser, rule))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 249, in __init__
    self._check_validators = self._get_check_validators()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 310, in _get_check_validators
    check_validators.append(_CheckValidator(self._schema, self._query_parser, check))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 328, in __init__
    self._check_query = self._query_parser.parse(check.test.query)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\queries\base.py", line 146, in parse
    return self._query_cache.setdefault(source, self._query_parser.parse(source))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\queries\xpath.py", line 69, in parse
    xpath_token = self._parser.parse(source)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\xpath2\xpath2_parser.py", line 508, in parse
    root_token = super(XPath1Parser, self).parse(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\tdop.py", line 497, in parse
    root_token = self.expression()
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\tdop.py", line 624, in expression
    left = self.token.nud()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\xpath30\_xpath30_operators.py", line 182, in nud_let_expression
    expr = self.parser.expression(5)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\tdop.py", line 627, in expression
    left = self.token.led(left)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\xpath31\_xpath31_operators.py", line 242, in led_arrow_operator
    self[:] = left, self.parser.expression(80)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\tdop.py", line 627, in expression
    left = self.token.led(left)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\xpath1\_xpath1_operators.py", line 186, in led
    self[:] = left, self.parser.expression(95)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\tdop.py", line 624, in expression
    left = self.token.nud()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\elementpath\xpath2\xpath2_parser.py", line 260, in nud_
    raise self.error('XPST0017') from None
elementpath.exceptions.ElementPathTypeError: 'xs:integer' constructor function at line 1, column 65: [err:XPST0017] Wrong number of arguments
```

**Comment by robbert-harms** [comment]
Thanks Martin, I'll update the package as soon as elementpath is updated. Can you link the to the issue in the elementpath library? Best, R.

**Comment by robbert-harms** [comment]
Thanks, I pushed out version 1.1.2 with the updated elementpath version requirement. That should fix it. I'll leave it open for you to confirm. Best, R.

**Comment by martin-honnen** [comment]
I get a very different error with the new version:

```
PS C:\Users\marti\OneDrive\Documents\schematron\examples\list-numbering> pyschematron.exe .\alphabetic-list1.xml .\list-check2.sch
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Scripts\pyschematron.exe\__main__.py", line 7, in <module>
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 328, in __call__
    raise e
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\core.py", line 721, in main
    return _main(
           ^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\cli.py", line 31, in validate
    result = validate_document(xml_documents[0], schema, phase=phase)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\__init__.py", line 43, in validate_document
    return validator.validate(xml_document)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\api.py", line 164, in validate
    validation_results = self._validator.validate_xml(xml_document)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 99, in validate_xml
    if node_result := self._validate_node(node, context):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 118, in _validate_node
    pattern_results.append(pattern_validator.validate(node, evaluation_context))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 207, in validate
    rule_result = rule_validator.validate(xml_node, context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 273, in validate
    check_results.append(check_validator.validate(xml_node, context))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 356, in validate
    text = self._rich_text_content_evaluator.evaluate(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyschematron\direct_mode\xml_validation\validators.py", line 526, in evaluate
    return (''.join(processed_text)).strip()
            ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, lxml.etree._Element found
```

I have tried it on two Windows 11 systems with Python 3.12 and having done `-m pip install --upgrade pyschematron` to update to the latest version.

**Comment by robbert-harms** [comment]
Thanks for the report. This was a different problem altogether. The issue was in your `<value-of select="term"/>` selector in the rich text. This returns a node and not a text content, which resulted in the problem that it could not concatenate the result string: "expected str instance".

I pushed out a new version which handles this situation more robustly. It should now be able to convert everything to a text value. Please try it.

The result however may not be exactly what you desire. You could consider changing `<value-of select="term"/>` to `<value-of select="xs:string(term)"/>` to return the actual string content of the term node instead of a serialized string representation of the entire node as you have it now.

**Comment by martin-honnen** [comment]
Thank you very much for your reply and fix, @robbert-harms.

Indeed pyschematron now handles the Schematron.

However, when I now return to my original validation attempt, with the XML being as shown below and the Schematron as shown below further down, I find that pyschematron says the XML is valid while Schxslt (both Schxslt 1.10.1 and Schxslt2 1.2.2) fire a failed assert.

And I think pyschematron should give that failed assert, too.

Let me know what you think and whether you would rather move that to a new issue.

XML:
```
<list>
  <item>
    <term>aa)</term>
    <p>jhjhjh hjkjkjkj</p>
  </item>
  <item>
    <term>cc)</term>
    <p>jhjhjh hjkjkjkj</p>
  </item>
  <item>
    <term>dd)</term>
    <p>jhjhjh hjkjkjkj</p>
  </item>
</list>
```

Schematron (reduced to the rule/assert where I get different results from pyschematron and Schxslt):
```
<schema xmlns="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt3">
    <pattern>
        <rule context="item[term[matches(., '^[a-z]+\)$')]][position() gt 1]">
            <assert test="
            let $index := term => substring-before(')') => string-to-codepoints(), 
            $index2 := preceding-sibling::item[1]/term => substring-before(')') => string-to-codepoints()
            return every $bool in for-each-pair($index, $index2, function($a, $b) { $a = $b + 1 }) satisfies $bool">item with <value-of select="string(term)"/> doesn't have the right term.</assert>
        </rule>
    </pattern>
</schema>
```

pyschematron SVRL
```
<?xml version='1.0' encoding='UTF-8'?>
<svrl:schematron-output xmlns:svrl="http://purl.oclc.org/dsdl/svrl" xmlns:sch="http://purl.oclc.org/dsdl/schematron" xmlns:xs="http://www.w3.org/2001/XMLSchema" phase="#DEFAULT">
  <svrl:metadata xmlns:dct="http://purl.org/dc/terms/" xmlns:skos="http://www.w3.org/2004/02/skos/core#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:pysch="https://github.com/robbert-harms/pyschematron">
    <dct:creator>
      <dct:agent>
        <skos:prefLabel>PySchematron 1.1.3</skos:prefLabel>
      </dct:agent>
    </dct:creator>
    <dct:created>2024-12-21T17:07:10.497114+01:00</dct:created>
    <dct:source>
      <rdf:Description>
        <dct:creator>
          <dct:Agent>
            <skos:prefLabel>PySchematron 1.1.3</skos:prefLabel>
          </dct:Agent>
        </dct:creator>
        <dct:created>2024-12-21T17:07:10.497114+01:00</dct:created>
      </rdf:Description>
    </dct:source>
  </svrl:metadata>
  <svrl:active-pattern documents="file:file:/C:/Users/marti/OneDrive/Documents/schematron/examples/list-numbering/alphabetic-list1.xml"/>
  <svrl:fired-rule context="item[term[matches(., '^[a-z]+\)$')]][position() gt 1]"/>
  <svrl:fired-rule context="item[term[matches(., '^[a-z]+\)$')]][position() gt 1]"/>
</svrl:schematron-output>
```

Schxslt2 SVRL:
```
<?xml version="1.0" encoding="UTF-8"?>
<svrl:schematron-output xmlns:err="http://www.w3.org/2005/xqt-errors" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:sch="http://purl.oclc.org/dsdl/schematron" xmlns:schxslt="http://dmaus.name/ns/2023/schxslt" xmlns:svrl="http://purl.oclc.org/dsdl/svrl" xmlns:xs="http://www.w3.org/2001/XMLSchema" phase="#ALL">
   <svrl:active-pattern documents=""/>
   <svrl:fired-rule xmlns="http://purl.oclc.org/dsdl/schematron" context="item[term[matches(., '^[a-z]+\)$')]][position() gt 1]"/>
   <svrl:failed-assert xmlns="http://purl.oclc.org/dsdl/schematron" test="             let $index := term =&gt; substring-before(')') =&gt; string-to-codepoints(),              $index2 := preceding-sibling::item[1]/term =&gt; substring-before(')') =&gt; string-to-codepoints()             return every $bool in for-each-pair($index, $index2, function($a, $b) { $a = $b + 1 }) satisfies $bool" location="/Q{}list[1]/Q{}item[2]">
      <svrl:text>item with cc) doesn't have the right term.</svrl:text>
   </svrl:failed-assert>
   <svrl:fired-rule xmlns="http://purl.oclc.org/dsdl/schematron" context="item[term[matches(., '^[a-z]+\)$')]][position() gt 1]"/>
</svrl:schematron-output>
```

Schxslt 1 SVRL:
```
<?xml version="1.0" encoding="UTF-8"?>
<svrl:schematron-output xmlns:error="https://doi.org/10.5281/zenodo.1495494#error" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sch="http://purl.oclc.org/dsdl/schematron" xmlns:schxslt-api="https://doi.org/10.5281/zenodo.1495494#api" xmlns:schxslt="https://doi.org/10.5281/zenodo.1495494" xmlns:svrl="http://purl.oclc.org/dsdl/svrl" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <svrl:metadata xmlns:dct="http://purl.org/dc/terms/" xmlns:skos="http://www.w3.org/2004/02/skos/core#">
      <dct:creator>
         <dct:Agent>
            <skos:prefLabel>SaxonJS/2.7</skos:prefLabel>
         </dct:Agent>
      </dct:creator>
      <dct:created>2024-12-21T17:12:56.397+01:00</dct:created>
      <dct:source>
         <rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/">
            <dct:creator>
               <dct:Agent>
                  <skos:prefLabel>SchXslt/1.10.1 SaxonJS/2.7</skos:prefLabel>
                  <schxslt.compile.typed-variables xmlns="https://doi.org/10.5281/zenodo.1495494#">true</schxslt.compile.typed-variables>
               </dct:Agent>
            </dct:creator>
            <dct:created>2024-12-21T17:12:56.199+01:00</dct:created>
         </rdf:Description>
      </dct:source>
   </svrl:metadata>
   <svrl:active-pattern documents="https://martin-honnen.github.io/schematron-fiddle/schxslt/schxslt-1.10.1/run-pipeline-for-svrl-and-apply-to-schema.xsl.sef.json"/>
   <svrl:fired-rule context="item[term[matches(., '^[a-z]+\)$')]][position() gt 1]"/>
   <svrl:failed-assert location="/Q{}list[1]/Q{}item[2]" test="             let $index := term =&gt; substring-before(')') =&gt; string-to-codepoints(),              $index2 := preceding-sibling::item[1]/term =&gt; substring-before(')') =&gt; string-to-codepoints()             return every $bool in for-each-pair($index, $index2, function($a, $b) { $a = $b + 1 }) satisfies $bool">
      <svrl:text>item with cc) doesn't have the right term.</svrl:text>
   </svrl:failed-assert>
   <svrl:fired-rule context="item[term[matches(., '^[a-z]+\)$')]][position() gt 1]"/>
</svrl:schematron-output>
```

**Comment by martin-honnen** [comment]
I have now also tried to see whether I can reproduce the problem with pure elementpath but code like
```
from elementpath import select

from elementpath.xpath3 import XPath3Parser

from xml.etree import ElementTree

root = ElementTree.parse('sample-list1.xml')

result = select(root, """/*/item[term[matches(., '^[a-z]+\\)$')]][position() gt 1] ! (let $index := term => substring-before(')') => string-to-codepoints(), 
            $index2 := preceding-sibling::item[1]/term => substring-before(')') => string-to-codepoints()
            return every $bool in for-each-pair($index, $index2, function($a, $b) { $a = $b + 1 }) satisfies $bool)""", parser=XPath3Parser)

print(result)
```
outputs `[False, True]` so one assert should fail.

**Comment by robbert-harms** [comment]
I found the problem. Your assert query: 

```xml
<assert test="
            let $index := term => substring-before(')') => string-to-codepoints(), 
            $index2 := preceding-sibling::item[1]/term => substring-before(')') => string-to-codepoints()
            return every $bool in for-each-pair($index, $index2, function($a, $b) { $a = $b + 1 }) satisfies $bool">item with <value-of select="string(term)"/> doesn't have the right term.</assert>
```

returns a list of booleans instead of a single boolean. That is, the query results in something like "[False]" or "[True]", instead of "False", "True". I did not anticipate such a result, I thought the query results had to be a definite boolean. The fix is easy though, and I'll push it out later today.

Thanks a lot for your tests. They are more in depth than my own uses, and they make pyschematron more robust.

**Comment by robbert-harms** [comment]
Hi Martin, I pushed out a new version just now. On my machine I now get the same SVRL results as the other packages. Please test and see if it now also works for you. Thanks again for filing the bug.

**Comment by martin-honnen** [comment]
Yes, thank, Rob, all working fine now. Therefore closing the issue.
